name: mirror

on:
  push:

  pull_request:
  

env:
  MIRROR_URL: "git@github.com:EpitechPromo2025/B-CPP-500-STG-5-1-rtype-gabriel.ravier.git"
  EXECUTABLES: "binary"
  ARGUMENTS: ""

jobs:
  push_to_mirror:
    if: ${{ github.event_name == 'push' }}
    name: "Push all files to mirror specified"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
